# Generated by Django 4.2.2 on 2023-06-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nombre_processeur', models.IntegerField()),
                ('capacite_memoire', models.IntegerField()),
                ('capacite_stockage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeServeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
                ('date_lancement', models.DateField()),
                ('espace_memoire_utilise', models.IntegerField()),
                ('memoire_vive_necessaire', models.IntegerField()),
                ('serveur_lancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serveurapp.serveur')),
            ],
        ),
        migrations.AddField(
            model_name='serveur',
            name='type_serveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serveurapp.typeserveur'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('services', models.ManyToManyField(to='Serveurapp.service')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serveurapp.utilisateur')),
            ],
        ),
    ]
