# Generated by Django 4.2.2 on 2023-06-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serveurapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.ImageField(default='image.jpg', upload_to='logos/'),
        ),
    ]
